server:
  port: 8001
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  application:
    name: dataServer-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: bigdata
    gateway:
      routes:
        - id: dataServer-quotoConfig
          uri: lb://dataServer-quotoConfig
          predicates:
            - Path=/dataservice/**
        - id: dataServer-roc
          uri: lb://dataServer-quotoRoc
          predicates:
            - Path=/roc/quoto/*
        - id: dataServer-chatbot
          uri: lb://dataServer-quotoChatbot
          predicates:
            - Path=/chatbot/**
        - id: dataServer-search
          uri: lb://dataServer-quotoSearch
          predicates:
            - Path=/search/**
        - id: dataServer-standardManage
          uri: lb://dataServer-standardManage
          predicates:
            - Path=/standard/**
        - id: dataServer-quotoManage
          uri: lb://dataServer-quotoManage
          predicates:
            - Path=/quotoManage/**
        - id: dataServer-labelManage
          uri: lb://dataServer-labelManage
          predicates:
            - Path=/label/**,/tag/**
        - id: dataServer-datart
          uri: lb://datart-server
          predicates:
            - Path=/api/v1/**
