spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.162:8848
        group: bigdata
  redis:
    host: 172.16.24.231
    port: 6379
configDbUrl: jdbc:mysql://172.16.31.145:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=false
configDbAccount: root
configDbPassword: root