server:
  port: 8078
spring:
  application:
    name: dataservice-common
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: bigdata
  redis:
    host: localhost
    port: 6379
configDbUrl: jdbc:mysql://localhost:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=false
configDbAccount: xxxx
configDbPassword: xxxx