server:
  port: 8070
spring:
  application:
    name: dataServer-quotoRoc
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: bigdata
  redis:
    host: localhost
    port: 6379
configDbUrl: jdbc:mysql://localhost:3306
configDbAccount: root
configDbPassword: root
dbUrl: jdbc:clickhouse://localhost:8123
dbAccount: default
dbPassword: 123456