spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.162:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
elasticsearch:
  host: 10.51.202.2
  port: 9400
hbase:
  quorum: 10.51.202.37:2181,10.51.202.38:2181,10.51.202.39:2181
dataServiceUrl: http://172.16.31.96:30515
ckDataSetDB: dataset
ckUrl: jdbc:clickhouse://172.16.31.147:8123
ckUser: default
ckPassword: 123456
hiveUrl: jdbc:hive2://172.16.31.145:10000
hiveUser: hive
hivePassword: Cm@456123