spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.146:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_label?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
elasticsearch:
  host: 10.51.202.2
  port: 9400
hbase:
  quorum: 172.16.23.37:2181,172.16.23.38:2181,172.16.23.39:2181