spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-client.nacos:8848
        group: dataservice-232
        namespace: dfa8081f69a4d787646c492a6faa83decbbecbda
  datasource:
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: bigdata-mysql-cloud1688
    driver-class-name: com.mysql.jdbc.Driver
elasticsearch:
  host: 10.51.202.2
  port: 9400
hbase:
  quorum: 172.16.23.37:2181,172.16.23.38:2181,172.16.23.39:2181
dataServiceUrl: http://bigdata-service-gw:8001
ckDataSetDB: dataset
ckUrl: jdbc:clickhouse://clickhouse.cloudminds.com:9090
ckUser: distributed-write
ckPassword: CloudMinds#
hiveUrl: jdbc:hive2://172.16.23.37:10000
hiveUser: dataserver
hivePassword: dataserver