server:
  port: 8076
spring:
  application:
    name: dataServer-quotoSearch
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        group: bigdata
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8