spring:
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      location: /home/qiong.tan/dataservice/markdowFile/
  resources:
    static-locations: classpath:static/,file:/home/qiong.tan/dataservice/markdowFile
  mvc:
    static-path-pattern: /**
