spring:
  datasource:
    url: jdbc:mysql://kubernetes-prod-3.cloudminds.com:31574/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: bigdata-mysql-cloud1688
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      location: /home/qiong.tan/markdowFile
  resources:
    static-locations: classpath:static/,file:/home/qiong.tan/markdowFile
  mvc:
    static-path-pattern: /**
