spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.146:8848
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_rule?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
hueUrl: http://cdh-slave01.cloudminds.com:8888/cloudminds/dataspec/#/