spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.cloudminds.com
  datasource:
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_rule?characterEncoding=utf8&useSSL=true
    username: root
    password: bigdata-mysql-cloud1688
    driver-class-name: com.mysql.jdbc.Driver