server:
  port: 8073
spring:
  profiles:
    active: dev
  application:
    name: dataServer-standardManage
  cloud:
    nacos:
      discovery:
        group: bigdata
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8