server:
  port: 8073
spring:
  application:
    name: dataServer-standardManage
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ldap:
    urls: ldap://l-172016023039.cloudminds.com:389
    base: dc=cloudminds,dc=com
    username: uid=hue,ou=People,dc=cloudminds,dc=com
    password: hue123
  mail:
    username: ops.bigdata@cloudminds.com.cn
    password: Cloudbigdata1688
    host: mail.cloudminds.com.cn
    port: 25
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.162:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_rule?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
hueUrl: http://cdh-slave01.cloudminds.com:8888/cloudminds/dataspec/#/