spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-client.nacos:8848
        group: dataservice-232
  datasource:
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_rule?characterEncoding=utf8&useSSL=true
    username: root
    password: bigdata-mysql-cloud1688
    driver-class-name: com.mysql.jdbc.Driver
hueUrl: http://l-172016031107-bigdata.cloudminds.com:8888/cloudminds/dataspec/#/