spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.23.85:31215
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_label?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver