spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.162:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_label?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dataServiceUrl: http://172.16.31.96:30515/data/quoto/tag