server:
  port: 8077
spring:
  application:
    name: dataServer-labelManage
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
metaJdbcConnet: jdbc:clickhouse://clickhouse.cloudminds.com:9090
metaJdbcUser: distributed-read
metaJdbcPassword: cloudminds123