server:
  port: 8077
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        group: bigdata
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
metaJdbcConnet: jdbc:clickhouse://clickhouse.cloudminds.com:9090
metaJdbcUser: distributed-read
metaJdbcPassword: cloudminds123
dataServiceUrl: http://172.16.23.83:30515/roc/quoto/tag