spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.162:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.16.24.231
    port: 6379
dataServiceUrl: http://172.16.23.83:30515
datahubToken: eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6ImJhNmQzZDRlLTY3M2ItNDMwYS1hNmI1LTg4YjkwZWM0YjQyOCIsInN1YiI6ImRhdGFodWIiLCJpc3MiOiJkYXRhaHViLW1ldGFkYXRhLXNlcnZpY2UifQ.hK4IHfjeiJSyDcUgc_8vExxEhiqUAR4Sd32Ql7jYjk4
datahubUrl: http://172.16.31.144:8080
datahubGraphqlUrl: http://172.16.31.144:9002/api/v2/graphql
hiveUrl: jdbc:hive2://172.16.31.145:10000
hiveUser: hive
hivePassword: Cm@456123
hiveMetastoreUrl: jdbc:mysql://172.16.31.145:3306/metastore?characterEncoding=utf8&useSSL=false
hiveMetastoreUser: root
hiveMetastorePassword: root
ckUrl: jdbc:clickhouse://172.16.31.147:8123
ckUser: default
ckPassword: 123456