spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.cloudminds.com
  datasource:
    url: jdbc:mysql://localhost:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver