spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-client.nacos:8848
        group: dataservice-232
        namespace: dfa8081f69a4d787646c492a6faa83decbbecbda
  datasource:
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: bigdata-mysql-cloud1688
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: bigdata-redis-master
    port: 6379
dataServiceUrl: http://bigdata-service-gw:8001
datahubToken: eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6ImJhNmQzZDRlLTY3M2ItNDMwYS1hNmI1LTg4YjkwZWM0YjQyOCIsInN1YiI6ImRhdGFodWIiLCJpc3MiOiJkYXRhaHViLW1ldGFkYXRhLXNlcnZpY2UifQ.hK4IHfjeiJSyDcUgc_8vExxEhiqUAR4Sd32Ql7jYjk4
datahubUrl: http://172.16.31.144:8080
datahubGraphqlUrl: http://172.16.31.144:9002/api/v2/graphql
hiveUrl: jdbc:hive2://172.16.23.37:10000
hiveUser: dataserver
hivePassword: dataserver
hiveMetastoreUrl: jdbc:mysql://172.16.23.37:3306/metastore?autoReconnect=true
hiveMetastoreUser: hive
hiveMetastorePassword: hive
ckUrl: jdbc:clickhouse://clickhouse.cloudminds.com:9090
ckUser: distributed-write
ckPassword: CloudMinds#