spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.cloudminds.com
        group: bigdata
  datasource:
    url: jdbc:mysql://bigdata-mysql:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: bigdata-mysql-cloud1688
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: bigdata-redis
    port: 6379
dataServiceUrl: http://172.16.23.83:30515
datahubToken: eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6ImJhNmQzZDRlLTY3M2ItNDMwYS1hNmI1LTg4YjkwZWM0YjQyOCIsInN1YiI6ImRhdGFodWIiLCJpc3MiOiJkYXRhaHViLW1ldGFkYXRhLXNlcnZpY2UifQ.hK4IHfjeiJSyDcUgc_8vExxEhiqUAR4Sd32Ql7jYjk4
datahubUrl: http://172.16.31.144:8080