server:
  port: 8071
spring:
  application:
    name: dataServer-quotoConfig
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: XXXX:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://XXXX:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: XXXXX
    port: 6379
dataServiceUrl: http://localhost:8070
datahubToken: eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6ImJhNmQzZDRlLTY3M2ItNDMwYS1hNmI1LTg4YjkwZWM0YjQyOCIsInN1YiI6ImRhdGFodWIiLCJpc3MiOiJkYXRhaHViLW1ldGFkYXRhLXNlcnZpY2UifQ.hK4IHfjeiJSyDcUgc_8vExxEhiqUAR4Sd32Ql7jYjk4
datahubUrl: http://172.16.31.144:8080
datahubGraphqlUrl: http://172.16.31.144:9002/api/v2/graphql
hiveUrl: jdbc:hive2://172.16.31.145:10000
hiveUser: hive
hivePassword: Cm@456123
hiveMetastoreUrl: jdbc:mysql://172.16.31.145:3306/metastore?characterEncoding=utf8&useSSL=false
hiveMetastoreUser: root
hiveMetastorePassword: root
ckUrl: jdbc:clickhouse://172.16.31.147:8123
ckUser: default
ckPassword: 123456
accessKey: JQBD6AYPLOLJD91MZUJA
secretKey: 4R0XVWCEEhdgN3cmHu3Wl9249apfq2QNU1yijmJ5
endpoint: https://s3.harix.iamidata.com
bucketName: bigdata
commonDataserviceUrl: /common/dataservice/data/
commonDataserviceName: common