server:
  port: 8071
spring:
  application:
    name: dataServer-quotoConfig
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
accessKey: JQBD6AYPLOLJD91MZUJA
secretKey: 4R0XVWCEEhdgN3cmHu3Wl9249apfq2QNU1yijmJ5
endpoint: https://s3.harix.iamidata.com
bucketName: bigdata

    