server:
  port: 8071
spring:
  application:
    name: dataServer-quotoConfig
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
accessKey: JQBD6AYPLOLJD91MZUJA
secretKey: 4R0XVWCEEhdgN3cmHu3Wl9249apfq2QNU1yijmJ5
endpoint: https://s3.harix.iamidata.com
bucketName: bigdata
commonDataserviceUrl: /common/dataservice/data/
commonDataserviceName: common