spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.146:8848
  datasource:
    url: jdbc:mysql://172.16.31.145:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.16.24.231
    port: 6379
dataServiceUrl: http://172.16.23.83:30515