server:
  port: 8071
spring:
  application:
    name: dataServer-quotoConfig
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: bigdata
  datasource:
    url: jdbc:mysql://localhost:3306/bigdata_dataservice?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
dataServiceUrl: http://localhost:8070
datahubToken: xxxxxx
datahubUrl: http://localhost:8080
datahubGraphqlUrl: http://localhost:9002/api/v2/graphql
hiveUrl: jdbc:hive2://localhost:10000
hiveUser: xxxx
hivePassword: xxxx
hiveMetastoreUrl: jdbc:mysql://localhost:3306/metastore?characterEncoding=utf8&useSSL=false
hiveMetastoreUser: xxxx
hiveMetastorePassword: xxxx
ckUrl: jdbc:clickhouse://localhost:8123
ckUser: xxxx
ckPassword: xxxx
accessKey: xxxxxxx
secretKey: xxxxxxx
endpoint: https://xxxxxxx
bucketName: bigdata