server:
  port: 8072
spring:
  profiles:
    active: test
  application:
    name: dataServer-quotoChatbot
  cloud:
    nacos:
      discovery:
        group: bigdata
  datasource: 
      url: jdbc:kylin://172.16.23.134:7070/sv
      username: ADMIN
      password: KYLIN
      driver-class-name: org.apache.kylin.jdbc.Driver